"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight, Check } from "lucide-react"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

const pdpImages = [
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tiramisu%20call-lUuDsqJtnJnmxBxxzCexOPwJx39kUR.webp", alt: "Prustlr Tiramisu Espresso protein oats range", label: "PDP / Tiramisu Espresso", title: "The ritual, made craveable." },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/sample%202-rZRR0HXkwFVdtSVI3GZzRSVXGWELis.webp", alt: "Prustlr ChocoRush Brownie protein oats pack with brownies", label: "PDP / ChocoRush Brownie", title: "Protein with a little more pleasure." },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Matcha%20-byfF2fsZjc8TApozUcKQizNcMLL0JV.webp", alt: "Prustlr Matcha Hazelnut protein oats pack with matcha and hazelnuts", label: "PDP / Matcha Hazelnut", title: "A calm, green start to the day." },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1-Z2FTWjzUn71bldNHsKDaXaJF4GhOiu.webp", alt: "Prustlr Discovery Pack product story", label: "PDP - Discovery Pack", title: "Benefits that scan in a second." },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2-4Mhdsk3jqNfSbIvOGGpXCLQo1t0PG0.webp", alt: "Prustlr clean sweet monkfruit product", label: "PDP / Clean sweet", title: "A better baseline for every bowl." },
]

const aPlusImages = [
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/monkfruite%20A%2B-i87IlqYJoZb8KZYASwVScPZoYMkVFG.webp", alt: "Prustlr Monkfruit A+ banner", label: "A+ / Brand story" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chocorush%20Brownie%20A%2B%203-6bjGsanpRxiW98GAyxrejry6ji5kgv.webp", alt: "Prustlr ingredients lineup showing oats, whey protein, monkfruit, milk powder, cocoa, chia, and chocolate chips", label: "A+ / Ingredient proof" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Monkfruit%20A%2B2-i4m9t0nIaxog2K1JqYwigDaWymuh23.webp", alt: "Prustlr Monkfruit A+ benefits layout", label: "A+ / Benefit system" },
]

const reelSources = [
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Discovery%20Motion%20ad-qLV8UA6m0LLt6iGwRwiISUJC0R0Ryr.mp4", label: "Discovery motion ad" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Discovery%20Pack%20ft%20hawa%20hawa%20buy%2020-BC3Y1Vr5V2J3FYL2fuKVinYj52GAKw.mp4", label: "Discovery Pack Hawa Hawa ad" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/igexport-DcijvHWuVkG-P3tNzdsroSAf7ctCiQnMUayg5f76PH.mp4", label: "Instagram export reel" },
]

const adCreatives = [
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/monkfruite%20ad.png-loeEcqWYpoxopPeJrQemb45FG4R1YH.jpeg", label: "Buy 1 Get 1" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chocorush%20Brownie%20Fav%2019201080-hWyl26kL8UwtFjwqFVlmq3jOH6ugG1.webp", label: "Favourite flavour" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20sale%20ad%202-jUpR2Zc76D5RAaBit8izJDe6ghdowm.webp", label: "Birthday sale" },
]

function SectionLabel({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) {
  return <div className="mb-10 grid gap-5 md:grid-cols-[1fr_1fr] md:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-[#4452FB]">{eyebrow}</p><h2 className="max-w-3xl font-poppins text-3xl font-semibold leading-[1.05] tracking-tight md:text-5xl">{title}</h2></div><p className="max-w-md text-sm leading-relaxed text-[#6B6B72]">{copy}</p></div>
}

const workflow = [
  ["01", "Product Intelligence", "Understand the SKU, flavour, audience, claims, and buying context before making anything."],
  ["02", "Visual Direction", "Build a visual language that makes the pack feel distinctive, appetising, and ownable."],
  ["03", "AI Production", "Create a high-volume first pass of product worlds, compositions, and campaign directions."],
  ["04", "Human Refinement", "Edit with taste: fix hierarchy, realism, spacing, details, and what the shopper actually needs to see."],
  ["05", "Creative Adaptation", "Turn the strongest ideas into PDP modules, A+ content, ads, reels, and reusable brand assets."],
]

export default function PrustlrCaseStudy() {
  return <main className="min-h-screen overflow-hidden bg-[#f5f5f7] text-[#0A0A0B]"><section className="relative px-6 pb-20 pt-8 md:px-10 md:pb-28 md:pt-10"><div className="mx-auto max-w-7xl"><div className="mb-20"><Navbar /></div><p className="mb-6 text-xs font-semibold uppercase tracking-[0.25em] text-[#4452FB]">Zeperai Media × Prustlr Protein Oats</p><div className="grid items-end gap-12 lg:grid-cols-[1.08fr_.92fr]"><div><h1 className="max-w-5xl font-poppins text-[clamp(3.4rem,8vw,8rem)] font-semibold leading-[.88] tracking-[-.07em]">From one protein oats pack to <span className="text-[#4452FB]">200+ pieces of content.</span></h1><p className="mt-8 max-w-2xl text-lg leading-relaxed text-[#6B6B72]">A creative system for Prustlr that made one product world stretch across ecommerce, marketplace, advertising, and social.</p></div><div className="rounded-[2rem] bg-[#101113] p-7 text-white md:p-9"><p className="mb-8 text-xs font-semibold uppercase tracking-[.22em] text-[#a8b0ff]">The brief</p><p className="font-poppins text-2xl font-semibold leading-tight md:text-3xl">Make a growing D2C food brand look as good as it tastes — without producing every asset from scratch.</p></div></div></div></section>

    <section className="border-t border-black/[.08] px-6 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.22em] text-[#4452FB]">The challenge</p><h2 className="font-poppins text-3xl font-semibold leading-tight md:text-5xl">Prustlr had the product. The content system had to catch up.</h2></div><div className="space-y-6 text-lg leading-relaxed text-[#6B6B72]"><p>Protein oats are a crowded category. The pack has to communicate flavour, function, trust, and appetite in a few seconds — across screens, marketplaces, and feeds.</p><p>The traditional route is heavy: photographer, studio, props, art direction, retouching, reshoots, and a new production cost every time the brief changes.</p><p>That process can work for one hero shoot. It is not built for the volume and speed a D2C brand needs to keep learning.</p></div></div></section>

    <section className="bg-[#e9e9ec] px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><p className="mb-4 text-xs font-semibold uppercase tracking-[.22em] text-[#4452FB]">The ZeperAI approach</p><h2 className="font-poppins text-4xl font-semibold leading-[.98] tracking-tight md:text-7xl">AI does the heavy lifting. <span className="text-[#4452FB]">Human direction does the thinking.</span></h2><p className="mt-8 max-w-2xl text-lg leading-relaxed text-[#6B6B72]">We used AI to expand the production surface, not to replace taste. Every output was directed, selected, refined, and adapted around the product and the buyer.</p></div><div className="mt-16 grid gap-3 md:grid-cols-5">{workflow.map(([number, title, copy]) => <article key={number} className="rounded-[1.5rem] bg-white p-5"><p className="font-mono text-xs text-[#4452FB]">{number}</p><h3 className="mt-12 font-poppins text-xl font-semibold leading-tight">{title}</h3><p className="mt-4 text-sm leading-relaxed text-[#6B6B72]">{copy}</p></article>)}</div></div></section>

    <section className="bg-[#4452FB] px-6 py-20 text-white md:px-10 md:py-28"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="mb-5 text-xs font-semibold uppercase tracking-[.22em] text-white/70">The result</p><p className="font-poppins text-[clamp(4rem,12vw,10rem)] font-semibold leading-[.8] tracking-[-.08em]">200+</p><p className="mt-5 max-w-md text-lg text-white/80">creative assets built from one product foundation — ready to work across the funnel.</p></div><div className="grid max-w-xl gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-black/15 p-5"><p className="font-poppins text-2xl font-semibold">More surfaces</p><p className="mt-2 text-sm text-white/70">One visual language across PDP, A+, ads, and social.</p></div><div className="rounded-2xl bg-black/15 p-5"><p className="font-poppins text-2xl font-semibold">Less reinvention</p><p className="mt-2 text-sm text-white/70">A reusable system instead of isolated one-off assets.</p></div></div></div></section>

    <section className="px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><SectionLabel eyebrow="Product photography" title="Make the product feel at home in the shopper's world." copy="Flavour-led product worlds gave each SKU a distinct mood while keeping the pack, serving, and promise clear."/><div className="grid gap-4 md:grid-cols-3">{pdpImages.slice(0, 3).map((tile) => <article key={tile.label} className="group relative aspect-square overflow-hidden rounded-[1.5rem] bg-[#dce8d8]"><Image src={tile.src} alt={tile.alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-5 pt-14 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/70">{tile.label}</p><h3 className="mt-2 font-poppins text-xl font-semibold leading-tight">{tile.title}</h3></div></article>)}</div></div></section>

    <section className="border-t border-black/[.08] px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><SectionLabel eyebrow="Ecommerce / PDP" title="A product page that makes the morning ritual tangible." copy="The PDP system turns flavour, ingredients, benefits, and discovery into a story that is easy to scan and hard to forget."/><div className="grid gap-4 md:grid-cols-12">{pdpImages.slice(3).map((tile, index) => <article key={tile.label} className={`${index === 0 ? "md:col-span-12" : "md:col-span-6"} group relative aspect-[16/8] overflow-hidden rounded-[1.5rem] bg-[#dce8d8]`}><Image src={tile.src} alt={tile.alt} fill sizes="(max-width: 768px) 100vw, 70vw" className="object-cover transition duration-700 group-hover:scale-[1.02]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-5 pt-14 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/70">{tile.label}</p><h3 className="mt-2 font-poppins text-xl font-semibold leading-tight">{tile.title}</h3></div></article>)}</div></div></section>

    <section className="bg-[#e9e9ec] px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><SectionLabel eyebrow="Amazon A+" title="Turn product information into purchase confidence." copy="A+ modules made the ingredients, benefits, and brand point of view feel clear, credible, and easy to browse."/><div className="grid gap-4">{aPlusImages.map((tile) => <article key={tile.label} className="group relative aspect-[2.5/1] overflow-hidden rounded-[1.5rem] bg-white"><Image src={tile.src} alt={tile.alt} fill sizes="100vw" className="object-cover transition duration-700 group-hover:scale-[1.02]" /><p className="absolute left-5 top-5 rounded-full bg-black/70 px-3 py-2 text-[10px] font-semibold uppercase tracking-[.18em] text-white backdrop-blur">{tile.label}</p></article>)}</div></div></section>

    <section className="bg-[#151518] px-6 py-24 text-white md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><SectionLabel eyebrow="Advertising" title="Creative built to earn the next second." copy="Campaign-ready formats made flavour, offer, and product value land in the first frame — then adapt across placements."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{adCreatives.map((tile) => <article key={tile.label} className="relative aspect-[9/16] overflow-hidden rounded-[1.5rem] bg-[#2b2b30]"><img src={tile.src} alt={tile.label} className="h-full w-full object-cover" /><p className="absolute left-4 top-4 rounded-full bg-black/65 px-3 py-2 text-[10px] font-semibold uppercase tracking-[.18em] text-white backdrop-blur">{tile.label}</p></article>)}</div></div></section>

    <section className="px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><SectionLabel eyebrow="Video & content production" title="Give the product a reason to move." copy="Short-form edits turn the same creative foundation into motion, offer moments, and repeatable social formats."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{reelSources.map((reel) => <article key={reel.label} className="overflow-hidden rounded-[1.5rem] bg-[#101113]"><video src={reel.src} controls muted playsInline className="aspect-[9/16] h-full w-full object-cover" aria-label={reel.label} /></article>)}</div></div></section>

    <section className="border-t border-black/[.08] px-6 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.22em] text-[#4452FB]">The production math</p><h2 className="font-poppins text-4xl font-semibold leading-tight md:text-6xl">A traditional workflow could easily cross <span className="text-[#4452FB]">₹2L+.</span></h2></div><div className="space-y-5 text-sm leading-relaxed text-[#6B6B72]"><p>This is an estimated traditional production comparison — not a verified client saving or performance claim.</p><div className="space-y-3">{["Photographer + crew", "Studio, props, surfaces, and styling", "Retouching, reshoots, and adaptations", "Multiple shoots for multiple channels"].map((item) => <p key={item} className="flex items-center gap-3 border-b border-black/10 pb-3"><Check className="h-4 w-4 text-[#4452FB]" />{item}</p>)}</div></div></div></section>

    <section className="px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#4452FB] px-7 py-12 text-center text-white md:px-16 md:py-16"><p className="mb-5 text-xs font-semibold uppercase tracking-[.25em] text-white/70">The takeaway</p><h2 className="mx-auto max-w-4xl font-poppins text-4xl font-semibold leading-tight md:text-6xl">Your product doesn&apos;t need another photoshoot. It needs a creative system.</h2><p className="mx-auto mt-6 max-w-2xl text-white/80">We created and generated over 400 pieces of content for Prustlr, establishing the brand&apos;s visual foundations across ecommerce, marketplace, paid ads, and social.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-2 rounded-full bg-[#0A0A0B] px-6 py-4 text-sm font-semibold text-white">Work with ZeperAI <ArrowUpRight className="h-4 w-4" /></Link></div></section><Footer /></main>
}

<style jsx global>{`@media (max-width: 640px) { video { max-height: 72vh; } }`}</style>

