"use client"

import { FormEvent, useState } from "react"
import { ArrowUpRight, Check } from "lucide-react"

const challenges = ["I depend too much on referrals", "I’m not getting enough enquiries", "My website doesn’t convert", "My content gets engagement but few leads", "My ads aren’t working", "I need a complete marketing system"]

export function QualificationForm() {
  const [submitted, setSubmitted] = useState(false)
  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setSubmitted(true)
  }
  if (submitted) return <div className="rounded-3xl bg-[#E9EBFF] p-8 md:p-14"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#4452FB]">Thank you</p><h3 className="mt-4 font-poppins text-3xl font-bold">We have your studio details.</h3><p className="mt-4 max-w-lg leading-relaxed text-[#6B6B72]">We will review your current setup and get back with the next step for building your acquisition system.</p></div>
  return <form onSubmit={handleSubmit} className="rounded-3xl bg-[#0A0A0B] p-6 text-white md:p-12"><div className="mb-10 max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#8E98FF]">Start here</p><h3 className="mt-4 font-poppins text-3xl font-bold tracking-[-0.03em] md:text-5xl">Tell us about your studio.</h3><p className="mt-4 leading-relaxed text-white/60">We will review your information and recommend the right combination of content, ads, funnel, website, and nurture.</p></div><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-medium">Name<input required name="name" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/35 focus:border-[#8E98FF]" placeholder="Your name" /></label><label className="text-sm font-medium">Studio / business name<input required name="business" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/35 focus:border-[#8E98FF]" placeholder="Your studio" /></label><label className="text-sm font-medium">City / service area<input required name="location" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/35 focus:border-[#8E98FF]" placeholder="Mumbai, Bengaluru, etc." /></label><label className="text-sm font-medium">Website / Instagram<input name="website" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/35 focus:border-[#8E98FF]" placeholder="https://" /></label></div><fieldset className="mt-8"><legend className="text-sm font-medium">What is your biggest challenge right now?</legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{challenges.map((challenge) => <label key={challenge} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/75 has-[:checked]:border-[#8E98FF] has-[:checked]:bg-white/10"><input type="radio" name="challenge" value={challenge} required className="accent-[#8E98FF]" />{challenge}</label>)}</div></fieldset><label className="mt-8 block text-sm font-medium">Approximate monthly marketing budget<select name="budget" className="mt-2 w-full appearance-none rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-white outline-none focus:border-[#8E98FF]"><option className="text-black">Not sure yet</option><option className="text-black">₹25,000 – ₹50,000</option><option className="text-black">₹50,000 – ₹1,00,000</option><option className="text-black">₹1,00,000+</option></select></label><button className="mt-8 inline-flex items-center gap-3 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#0A0A0B] transition-transform hover:scale-[1.03]">Request my marketing plan <ArrowUpRight className="h-4 w-4" /></button></form>
}

export function TrustAndFaq({ onCta }: { onCta: () => void }) {
  const faqs = [{ q: "Do you only work with interior designers?", a: "Interior design is one of the niches we build dedicated systems for. We also work with related design-led businesses depending on the project." }, { q: "Do I need a new website?", a: "Not necessarily. We first assess your current website and recommend improvements or a dedicated landing page only when the structure limits conversion." }, { q: "Do you guarantee a certain number of clients?", a: "No. Performance depends on market, location, offer, pricing, sales process, and budget. We focus on building and improving the acquisition system." }, { q: "Is this a one-time project or monthly service?", a: "It can be structured as a project, ongoing retainer, or combination depending on what your business needs." }]
  return <><section className="px-6 py-24 md:py-32"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.28em] text-[#4452FB]">What happens next</p><h2 className="font-poppins text-4xl font-bold tracking-[-0.04em] md:text-6xl">A clear process, not another vague proposal.</h2></div><div className="mt-14 grid gap-4 md:grid-cols-5">{["Tell us about your business", "We review your setup", "We identify the gaps", "We recommend the system", "We build it"].map((step, i) => <div key={step} className="rounded-2xl border border-black/[0.1] p-5"><span className="text-sm font-semibold text-[#4452FB]">0{i + 1}</span><p className="mt-10 text-sm font-semibold">{step}</p></div>)}</div></div></section><section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto max-w-4xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.28em] text-[#4452FB]">Questions</p><h2 className="font-poppins text-4xl font-bold tracking-[-0.04em] md:text-6xl">Before we talk.</h2><div className="mt-12 divide-y divide-black/[0.1] border-y border-black/[0.1]">{faqs.map((faq) => <details key={faq.q} className="group py-6"><summary className="cursor-pointer list-none pr-8 font-poppins text-lg font-bold marker:hidden">{faq.q}</summary><p className="mt-4 max-w-2xl leading-relaxed text-[#6B6B72]">{faq.a}</p></details>)}</div><button onClick={onCta} className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#0A0A0B] px-5 py-3 text-sm font-semibold text-white">Build my client acquisition system <ArrowUpRight className="h-4 w-4" /></button></div></section></>
}
